spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=OneShop;encrypt=false;trustServerCertificate=true;sendStringParametersAsUnicode=true
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

spring.thymeleaf.cache=false

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

server.port=8080

jwt.secret=NDY4MTM3NzkzMTM5NzE0NDczNzk0NDU4NGEzMDY0Nzc0ZDYxNzU2NDQ1NDE0YzQyNDE0NDM5NDE=
app.cookie.secure=false

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=21MB

spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=supportoneshop@gmail.com
spring.mail.password=yqutjcsxmrxoyexo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.transport.protocol=smtp

shop.sepay.bank-code=VietinBank
shop.sepay.account-no=107885426583
shop.sepay.account-name=NGUYEN THI KHUYEN

app.mail.from-name=OneShop
app.mail.from-address=supportoneshop@gmail.com
app.mail.decorator.max-retries=2
app.mail.decorator.max-send-per-window=5
app.mail.decorator.limit-window-minutes=15

server.forward-headers-strategy=framework